// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emmlxczljiqfssipmevx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbWx4Y3psamlxZnNzaXBtZXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTYwOTcsImV4cCI6MjA3MzgzMjA5N30.bwXODk0kk-mpCrhsPAhJWxuaApeJHQc1pmJMzYiVJNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});